### ISSUE TITLE
Don't use a file extension for DllImport to enable cross platform PInvoke

### ISSUE THREAD

**Issue by SneWs** [flibitijibibo/SDL2-CS#104]
#region SDL2# Variables

		/// <summary>
		/// Used by DllImport to load the native library.
		/// </summary>
		private const string nativeLibName = "SDL2.dll";

		#endregion

If you drop the .dll from the above declaration you would then rely on the platform to do the correct thing. Eg. Load a .so for Linux and .dylib on OSX. See http://www.mono-project.com/docs/advanced/pinvoke/ for details.

**Comment by flibitijibibo** [comment]
I would agree if I used "libSDL2.so", for example. However, I tend to ship with what gets checked by native binaries when linking via -lSDL2, which is what you see in the dllconfig.

That said, I'm pretty sure Mono swaps the extension already. I've done this for other libs without trouble. Is this Yet Another CoreCLR thing?

**Comment by SneWs** [comment]
I seem to be hitting this issue using Xamarin Studio on OSX.

**Comment by flibitijibibo** [comment]
Strange, where did you build SDL from? You should have a libSDL2-2.0.0.dylib in build/.libs...

**Comment by SneWs** [comment]
I didn't build SDL2 myself. I grabbed it via homebrew (http://brew.sh).
Will have to try to build it myself and re-try this. Probably related the brew binaries.

**Comment by flibitijibibo** [comment]
If you grab SDL from Mercurial then the CMake file should work beautifully; we hit a couple snags with 2.0.4 but it's since been fixed. It's a good alternative to the fat binary scripts which can be a bit wonky if you don't have the right SDK versions installed.

Alternatively you can steal the bins from FNA's prebuilt binaries:

http://fna.flibitijibibo.com/archive/fnalibs.tar.bz2

**Comment by SneWs** [comment]
I'll give that a try, thx!

**Comment by SneWs** [comment]
Seems to be working now. Thx for the info.
