### ISSUE TITLE
Help (explanations ?)  regarding SDL_RWops

### ISSUE THREAD

**Issue by HebuSan** [flibitijibibo/SDL2-CS#107]
Hi,

While porting Lazy Foo tutorial, noticed that SDL_RWFromFile is not available.
After looking at the code, seems you made it internal, for use only with "THIS IS A PUBLIC RWops FUNCTION!".

1. When I look at the 5 public functions you expose, and the way they call the "INTERNAL_SDL_RWFromFile", I see nothing special that should refrain me from making the SDL_RWFromFile public (to use it in the same way that it is used in LazyFoo's tutorial 33).

2. I see no reference to SDL_RWclose. Even as an "Internal" function. IF I am not wrong, then how can you free pointers allocated with INTERNAL_SDL_RWFromFile ?

I found, on the tao Framework github, that they are not so carefull about how they use SDL_RWFromFile. On the other hand, they also never call SDL_RWclose (maybe because it is while unit testing, so they dont care and quit the test ...).

As I am a big Noob regarding SDL, am I missing something huge regarding calls to  SDL_RWFromFile complexity ? And regarding how SDL_RWclose should be used ?

If there is no specific complexity regarding how these calls should be handled, and if it just a matter of time for testing, is there a way to help for refering / testing it ?

Thanks a lot for you great work.

**Comment by flibitijibibo** [comment]
I recommend not using SDL_RWops specifically because C# already has standard I/O, making RWops unnecessary (similar to SDL_Thread). The only reason you should use it is if you are interacting with a function that requires RWops, and all the functions we currently expose have a parameter that automatically closes the structure, such as this one used in FNA:

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L1012
https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L1018

If you can help it, try using C# standard functions instead of SDL's unless they're distinctly less portable (which, as far as I know, is just System.Drawing which depends on the awfully unportable libgdiplus; you can use SDL_Surface interop instead).

**Comment by HebuSan** [comment]
Hi,

thanks again for your quick answers.

1. Regarding SDL_RWFromFile, makes sense, so will do this way.
2.a. Forgot you also are behind FNA, should have checked by myself in your repository. Thx for the links, really interesting.
2.b. My point was rather that, in the 5 "internal" fonctions you made, you never free the SDL_RWops IntPtr you retrieve from the INTERNAL_SDL_RWFromFile, and that you give to other SDL calls. That is why i THOUGHT SDL_RWclose call (and binding) was missing somewhere. Since then I checked the functions in the SDL Wiki, seems they handle by themselves "freeing" the SDL_RWops they get in parameters. So everything is clear to me now.

Issue can be closed, sorry for the bother.
