### ISSUE TITLE
No OpenGL implementation ?

### ISSUE THREAD

**Issue by badonkadong** [flibitijibibo/SDL2-CS#116]
so i found the basic pinvokes for openGL init
and made it go like this

sdlResult = SDL.SDL_GL_SetAttribute(SDL.SDL_GLattr.SDL_GL_CONTEXT_MAJOR_VERSION, 3);
			sdlResult = SDL.SDL_GL_SetAttribute(SDL.SDL_GLattr.SDL_GL_CONTEXT_MINOR_VERSION, 2);
			sdlResult = SDL.SDL_GL_SetAttribute(SDL.SDL_GLattr.SDL_GL_CONTEXT_PROFILE_MASK, (int)SDL.SDL_GLprofile.SDL_GL_CONTEXT_PROFILE_CORE);
			sdlResult = SDL.SDL_GL_SetAttribute(SDL.SDL_GLattr.SDL_GL_DOUBLEBUFFER, 1);
			_CurrentWindow = SDL.SDL_CreateWindow("", SDL.SDL_WINDOWPOS_CENTERED, SDL.SDL_WINDOWPOS_CENTERED, W, H,
SDL.SDL_WindowFlags.SDL_WINDOW_SHOWN | SDL.SDL_WindowFlags.SDL_WINDOW_OPENGL);

			//OpenGL Context creation
			_GL_Context = SDL.SDL_GL_CreateContext(_CurrentWindow);

but i could not find any glDrawSomething or glSetMatrixSomething functions
are you planing to implement them in the near future ?

**Comment by flibitijibibo** [comment]
We used to have them in the form of MiniTK but that has since been removed. It's recommended that you load your own GL entry points with SDL_GL_GetProcAddress, like we do in FNA...

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/OpenGLDevice_GL.cs

... but there is also MiniTK as a separate thing if you want it:

https://github.com/dan200/MiniTK
