### ISSUE TITLE
Using unsafe pointers rather than IntPtr if struct type matters?

### ISSUE THREAD

**Issue by bplu4t2f** [flibitijibibo/SDL2-CS#123]
This is first and foremost a question about why the design was chosen the way it is, or maybe if I'm overlooking something.

Take `IMG_Load` for example, which currently returns `IntPtr` (is actually `SDL_Surface*`). In practice, you'd need to access the struct's members to work with them reasonably, at least `format`, `w`, `h`. That's rather ugly if you have to something like `(SDL_Surface)Marshal.PtrToStructure(surface_ptr, typeof(SDL_Surface))` and then subsequently the same for the `SDL_PixelFormat`. It is also a performance degradation, even though anyone would probably argue that performance isn't the main priority considering this is C# (on the other hand I personally think that argument is starting to get a bit stale and I'd say why not use the language's features to avoid most of that performance drop in the first place).

An alternative would be to use more `unsafe` things, like defining `unsafe SDL_Surface* IMG_Load` rather than `IntPtr IMG_Load`, and similarly define the `struct SDL_Surface` as `unsafe` and put a `SDL_PixelFormat* format` in there. User code consuming those APIs looks a lot like C (which I think is good considering what we're *actually* dealing with because it's simple and more straight-forward. Also `null` is a lot nicer than `IntPtr.Zero`, come on).

Using `IntPtr` here isn't any "safer" than the "unsafe" stuff either if you need to do manual Marshalling stuff anyway, and unsafe pointer types actually more type-*safe* (rather than *unsafe*) and IMO easier to understand and maintain. The one big reason I see against it is that users can only consume it if they mark their own code `unsafe` as well (which is something I don't have any problem with, but I can see where they're coming from).

So I've already done a bunch of overloads for my quick and dirty project, but I'm wondering if I should systematically generate those in an extra class for all affected functions and structs and maybe release that on github. On the other hand, I'm wondering why this hasn't been done before (because I guess it has at least been considered), and if I'm going to shoot myself in the foot or wander off into a dead end, I just don't know it yet.

**Comment by flibitijibibo** [comment]
The decision ultimately was "it's easier for applications to go into `unsafe` than it is for applications to opt out of `unsafe`." So for example, if you look at FNA's surface scaling...

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L1262

... there's only one real place where `unsafe` is needed, and it's not that big of a deal to just go into an unsafe block for the one call we do. On the other hand, take _all_ of the other functions in that file that do NOT use unsafe code, and consider that forcing the API to be unsafe basically forces _all_ of the code to be in unsafe mode when it really doesn't need to be.

Personally I don't care all that much about it since I live in C most of the time anyway, but for someone that just wants to get an opaque pointer and move on with their life it's less typing for them to endure, and for those that need more control they can spend the extra characters making one or two type casts to get the control they need. Not to mention, this sort of code is typically abstracted away anyhow, so all your unsafe stuff happens at once and not throughout the program scattered about...

**Comment by bplu4t2f** [comment]
I understand that argument. I do agree that it should be opt-in rather than opt-out. As it turns out it *is* very annoying if you don't need it.

Yet I can't help but feel like this is is just like designing a (pure) C API such that everything is `void*` with the argument that most of the time you just need an opaque pointer, and otherwise you can just cast it.

I have to think about this some more. I do like to use C# bindings that are as close as possible to the C API.
