### ISSUE TITLE
.net core

### ISSUE THREAD

**Issue by dpeter99** [flibitijibibo/SDL2-CS#129]
Should this wrapper work in a .net core app
If so what setup does it need?
I currently have a .net core console app that i would like to open the "Game" window from. 

```
static void Main()
{
  SDL2.SDL.SDL_Init(SDL2.SDL.SDL_INIT_VIDEO);

  Console.ReadLine();
}
```

But i get the following error: ``System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)'
``

**Comment by flibitijibibo** [comment]
It’s probably one of three things

1. You used SDL2-CS instead of SDL2-CS.Core
2. The architecture of your exe doesn’t match the architecture of SDL2-CS.dll
3. The architecture of the native code (SDL2.dll) doesn’t match the managed code (your exe and SDL2-CS.dll).

To be sure, just make everything x64-only and it should be fine after that.

**Comment by dpeter99** [comment]
Yeah figured it out. I needed the .dll 
I thought it was included
