### ISSUE TITLE
Why the parameter of the function is “IntPtr” instead of “ref”

### ISSUE THREAD

**Issue by Ouyang-Zhaoxing** [flibitijibibo/SDL2-CS#130]
For example "SDL_RenderCopy"
Why does the Rect parameter use "IntPtr rect" instead of "ref SDL.SDL_Rect rect"?
However, some functions use the second method and do not quite understand the reason.

**Comment by flibitijibibo** [comment]
This is one of those annoying things about C# - we need a version of each function that does both IntPtr and `ref` because for `ref` we can't pass `null`, and SDL has default behaviors for when certain parameters are null (for example, a `null` SDL_Rect might tell SDL to just copy the whole surface instead of a subregion).

This is definitely an area I haven't covered for sure - if you find that there's a parameter you want to be `null` (or not!) and the function isn't there, send the added function my way and I'll merge it.

**Comment by Ouyang-Zhoxing** [comment]
@flibitijibibo Thank you for your answer.
