### ISSUE TITLE
Missing SDL API/features

### ISSUE THREAD

**Issue by WardBenjamin** [flibitijibibo/SDL2-CS#136]
Is SDL2-CS _actually_ up to date? For the last version (2.0.8) you just updated the patch level integer, and didn't actually add any code for the huge list of features:

From the changelog:
```
Added SDL_fmod() and SDL_log10()
Each of the SDL math functions now has the corresponding float version
Added SDL_SetYUVConversionMode() and SDL_GetYUVConversionMode() to control the formula used when converting to and from YUV colorspace. The options are JPEG, BT.601, and BT.709
```
Etc.

I came across this when trying to use SDL2-CS for Vulkan purposes, but I couldn't retrieve the hInstance via `SDL_GetWindowWMInfo` to create a Vulkan surface since the `SDL_SysWMinfo.info.win.hinstance` field is missing! 

How can these bindings be updated to properly support new SDL versions?

**Comment by flibitijibibo** [comment]
Just add what you need and it’ll work. That’s what’s nice about SDL2# - add it as it appears in the headers.

Don’t worry about stdlib though - just get the Vulkan and YUV stuff in and I’ll merge it. tbh I was just getting that other guy off my back since he asked for a version update and not a missing feature, so that’s exactly what I did :trollface:

**Comment by flibitijibibo** [comment]
Oh also, if it’s just the WSI CreateSurface you need, SDL_Vulkan_CreateSurface is already in.

**Comment by flibitijibibo** [comment]
Closing due to old age, missing functions can be added/requested as needed.
