### ISSUE TITLE
Confused about how to use SDL_UpdateTexture

### ISSUE THREAD

**Issue by graspee** [flibitijibibo/SDL2-CS#142]
I'm not that great with C# so apologies. 
I'm having trouble with SDL_UpdateTexture, needing to pass it an IntPtr for the pixels.
At first I tried making an array of Uint32 but it didn't work because, I think, you can't take the address of a managed type?
So obviously what you need to do is create an unmanaged block of memory to pass in. I got as far as documentation for the Marshal class but it seemed rather complex- surely this isn't how you intended us to use UpdateTexture I began to think.
I was then looking at the SDL_malloc function and getting confused trying to pass it the size of block I wanted, but the size is specified as an IntPtr so eventually my confused head worked out it was wanting to pass me back the size it had allocated rather than me specifying one?

As you can see, I'm a noob and I apologise for wasting your time. I just want to blit pretty pixel pictures to the screen faster than doing RenderDrawPoint 640*360 times. :)

Thanks in advance for any help.

**Comment by flibitijibibo** [comment]
For arrays based on value types you can get the address like this:

```
using System.Runtime.InteropServices;
byte[] managed = new byte[1];
GCHandle handle = GCHandle.Alloc(managed, GCHandleType.Pinned);
IntPtr ptr = handle.AddrOfPinnedObject();
handle.Free(); // Don't forget to free this when you're done!
```

It's kind of complicated, but if you're working with data in managed code that's the way it's usually done... there are nicer ways to work with memory, but I'm a C guy rather than a C# guy so I'm biased:

```
using System.Runtime.InteropServices;
IntPtr ptr = Marshal.AllocHGlobal(69);
unsafe
{
    // You can operate on arrays like this!
    byte* bPtr = (byte*) ptr;
    bPtr[0] = 69;
}
Marshal.FreeHGlobal(ptr); // Don't forget to free!
```

This one is my favorite that someone else showed me:

```
using System.Runtime.InteropServices;
private unsafe void SomeFunction()
{
    byte* ptr = stackalloc byte[69];
    SomeOtherFunction((IntPtr) ptr);
    // Don't have to free, ptr is deallocated upon function exit
}
```

Many of FNA's libraries (including SDL2#) use malloc or SDL_malloc but that's because of very specific and very ugly reasons that hopefully you'll never ever run into. Whenever you see IntPtr for anything _other_ than a block of memory, it's typically referencing a `size_t` value, and IntPtr is the best C# has to represent that.

**Comment by graspee** [comment]
Thanks very much for taking the time to answer my naive question and thanks more generally for making SDL 2 available to C# users. I know it's a lot of work.

**Comment by flibitijibibo** [comment]
Thankfully because we don't actually change anything from the C headers it's very easy to maintain SDL2#! C# users aren't typically used to pointers but it's never too late to learn about them.
