### ISSUE TITLE
How to make the program look for the SDL2.dll in the build output folder?

### ISSUE THREAD

**Issue by Revolt64** [flibitijibibo/SDL2-CS#143]
Hello there.

My program fails to find the SDL2.dll unless it is installed in the system.

When the dll is located in the same directory as my application (and not installed system wide) I get the following error:

`System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies.`

Is there any way to make it look in the output directory first? And fallback to the system wide dll if it doesn't find it inside that folder?

Thank you

**Comment by flibitijibibo** [comment]
On Windows I would expect it to search the exe folder already, per the usual OS behavior. On Linux it may be easier to just install SDL2 from your distro and use that since it's not any different from the one I ship with fnalibs, and for macOS you have to set DYLD_LIBRARY_PATH first:

https://github.com/AndrewRussellNet/FNA-Template#linuxmacos-setting-the-library-path-for-debugging

(The folder may not be `osx/` in your case, but you get the idea.

**Comment by Revolt64** [comment]
Thanks for the info @flibitijibibo 

So let's use macOS as the example here. Setting the DYLD library path could mitigate having to have SDL installed on the target system whilst I'm debugging, but I'm more concerned about shipping my application.

It would be preferable if I could just ship the SDL dll's with the application to prevent another install step for the user. I guess I could create an installer .pkg that does the installing SDL dll's to the users system as a post installation step, but it would be subjectively "better" if there was a way to just have the binary look for the SDL libs in the executable directory.

Am I just sod out of luck with this goal? If there's no way around it and it's one of those "it is how it is" situations, that's fine, I just want to avoid going on a wild goose chase.

Thanks!

**Comment by flibitijibibo** [comment]
This page should be useful:

https://github.com/FNA-XNA/FNA/wiki/3:-Distributing-FNA-Games

**Comment by Revolt64** [comment]
Thanks very much.
