### ISSUE TITLE
Add bindings for SDL_RW* macros.

### ISSUE THREAD

**Issue by ru-ace** [flibitijibibo/SDL2-CS#156]
Hi!
Could you please pay your attention to this [feature request for SDL2lib](https://bugzilla.libsdl.org/show_bug.cgi?id=4526#c2) and say:
is it possible to do what Sylvain offers?
```
Sylvain 2019-03-01 20:47:57 UTC
This could be added ...
but maybe:

1/ you can report that to one who does the wrapper so that it provides also the macros
2/ There is not SDL_RWseek but maybe it exposes things to call: (ctx)->seek(ctx, offset, whence)
```
Thanks!

**Comment by flibitijibibo** [comment]
It’s not entirely possible because function pointers are pretty obnoxious in C#. In FNA we have this...

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L1794

... but strongly recommend NOT reusing this since it’s very incomplete and may not always line up with the real RWops function.

C# streams are fine most of the time, the need for RWops in C# is usually very extreme (see our references to FakeRWops) and oftentimes unsafe (RWFromMem can potentially reference managed memory that isn’t properly pinned).

This is largely a WONTFIX on our end for the same reason we don’t implement SDL_Thread.

**Comment by ru-ace** [comment]
Could you please clear for me:
if this macros will be wrapping with functions like this:
```c
extern int SDL_RWseek(SDL_RWops *ctx, int offset,int whence)
{
  return (ctx)->seek(ctx, offset, whence)
}
```
Would it be easier to implement bindings for  SDL_RW*?

**Comment by flibitijibibo** [comment]
That would work, though I dunno if they’ll add those. You could throw it in a separate native DLL if you wanted.
