### ISSUE TITLE
No way to use SDL_RWops

### ISSUE THREAD

**Issue by masonwheeler** [flibitijibibo/SDL2-CS#83]
Trying to write a simple wrapper class that wraps a SDL_RWops in a System.IO.Stream descendant, but the SDL_RWops struct is not even defined in SDL2-CS, so I have no way to access anything.

**Comment by flibitijibibo** [comment]
I'm not sure what you mean... are you asking for the SDL_RWops struct members?

The way RWops should typically be used is like this:

https://github.com/flibitijibibo/FNA/blob/master/src/Graphics/Texture2D.cs#L449
https://github.com/flibitijibibo/FNA/blob/master/src/Graphics/Texture2D.cs#L504

You could possibly define somes callbacks to be used in the RWops struct...

https://hg.libsdl.org/SDL/file/e64d9374f1be/include/SDL_rwops.h#l52

... but I would leave it up to you to make this usable in a C# context. The only reason SDL_RWops is in SDL2# is because of the need to interop with SDL2 functions that depend on RWops in the way you see in FNA; were it up to me I'd leave that subsystem out entirely.

**Comment by masonwheeler** [comment]
Making the callbacks usable [is not all that difficult](http://msdn.microsoft.com/en-us/library/bfeyhsdy%28v=vs.110%29.aspx).

The examples given, using SDL_RWFromMem, work just fine if you have all of the existing memory and need to transfer it to a SDL_RWops, but not for the opposite operation: reading data from a SDL_RWops into memory.  That can only be done if you have access to the `read` member.  Since SDL_RWops is just a stream implementation in SDL, it should be trivial to wrap it in a `Stream` object, but to do that, first the struct needs to be exposed and the callbacks made available.

>The only reason SDL_RWops is in SDL2# is because of the need to interop with SDL2 functions that depend on RWops in the way you see in FNA; were it up to me I'd leave that subsystem out entirely.

Why would you want to leave out such an important part of SDL?

**Comment by flibitijibibo** [comment]
I mostly leave out elements of SDL2 that are already in C# by default, but like I said, if you think those parts have value, definitely send me the patches.

My logic behind keeping those parts out is that, for example, I could just use Stream by itself without having to worry about additional libraries, but if there's a maintainer for the RWops work, I'd be okay with having it in the wrapper. The point is that I wouldn't be the maintainer, and when there's a problem with those parts, I'd be the first to blame that maintainer in particular without involving myself in the bug report at all, other than the act of blaming the person responsible for that code.

But fortunately, none of that matters if the code Just Works(TM). I'll leave that up to you.

**Comment by flibitijibibo** [comment]
Closing due to old age.
