### ISSUE TITLE
SDL_GetBasePath() crashes in LPUtf8StrMarshaler.CleanUpNativeData

### ISSUE THREAD

**Issue by nickgravelyn** [flibitijibibo/SDL2-CS#89]
It looks like perhaps the marshaler isn't working correctly for output strings. From a quick debug session, it seems the IntPtr is not the same as the HGlobal you allocated, but rather the IntPtr passed to MarshalNativeToManaged. I don't know anything about custom marshalers (or specifically what this one is doing with the boolean flag) or else I'd try to actually address it.

Potentially worth noting is that I'm using VS2015 preview and .NET 4.5. Not sure if either of those would factor into this.

**Comment by flibitijibibo** [comment]
This call might need special treatment, as the pointer we get back from this function has to be freed by the application:

https://wiki.libsdl.org/SDL_GetBasePath

That bool is for cases like SDL_GetPlatform where the string is a const char*:

https://github.com/flibitijibibo/SDL2-CS/blob/master/src/SDL2.cs#L190

So it actually _should_ be okay here since we want to free that pointer, but why it's failing, I'm not sure. I tend to just roll my own version of this call...

CC: @jpernst

**Comment by flibitijibibo** [comment]
Also for what it's worth I think `AppDomain.CurrentDomain.BaseDirectory` does the same thing in standard C#... it's what FNA uses for the TitleContainer, at least.

**Comment by nickgravelyn** [comment]
Yeah I suppose I could use that. The same issue is hit with SDL_GetPrefPath, though.

To get unblocked I just made versions of the both functions that return a regular IntPtr and added SDL_free, then pulled out the code to get the UTF8 string from it. Simple enough and it's working.

**Comment by flibitijibibo** [comment]
I'm wondering if it's that Win32 uses LocalFree rather than just free for FreeHGlobal, because that pointer we're freeing is actually the original pointer from SDL, rather than the one AllocHGlobal pointer (that one actually looks more like a leak to me... looking into that as well). On Windows SDL_malloc()/SDL_free() are totally separate from the C runtime entirely, so this would explain why it crashes on Windows but not anywhere else.

I'll have a look at this now. Worst case, we drop the marshaler in favor of doing this by hand, being more careful about tracking unmanaged memory.

**Comment by flibitijibibo** [comment]
After testing this on Linux I'm now wondering...

What happens when you replace AllocHGlobal and FreeHGlobal with direct calls to malloc/free? You can nab the entry points from Vorbisfile#:

https://github.com/flibitijibibo/Vorbisfile-CS/blob/master/Vorbisfile.cs#L42

I dunno if this'll be any better for SDL2 Win32, but it's probably better than LocalFree.

**Comment by jpernst** [comment]
The best way to fix this is probably to just have the utf8 marshaller call SDL_free() instead of FreeHGlobal(), which will guarantee that it does the proper thing regardless of platform. The entire purpose of the CleanUpNativeData() method was to handle freeing SDL pointers as necessary and isn't used for anything else, so it should be perfectly save to call SDL_free directly.

**Comment by flibitijibibo** [comment]
Hm, very well. Here's a diff to use SDL's malloc/free instead:

http://www.flibitijibibo.com/sdlmalloc.diff

If this works for Windows I'll merge it into mainline right away.

**Comment by nickgravelyn** [comment]
That works for my case, at least.

**Comment by flibitijibibo** [comment]
Excellent. C# remains fired.

https://github.com/flibitijibibo/SDL2-CS/commit/2e9752838d11fbb3b9ed374659ce34a77b13ce66
